[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = "dummy-token"

[[plugins]]
  package = "@netlify/plugin-nextjs" 